# Short URLs: /w/Page_title -> index.php (same scheme as matchaflavoured.wiki and minecraft.wiki)
<Directory /var/www/html>
    RewriteEngine On
    RewriteRule ^w/(.*)$ index.php [L,QSA]
    RewriteRule ^/*$ index.php [L,QSA]
</Directory>
