<?php
# Matcha Flavoured Wiki — MediaWiki 1.45 configuration.
# Checked in; secrets below are for the local Docker instance only.
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgSitename = 'Matcha Flavoured Wiki';
$wgMetaNamespace = 'Matcha_Flavoured_Wiki';

$wgServer = getenv( 'MW_SERVER' ) ?: 'http://localhost:8080';
$wgScriptPath = '';
$wgArticlePath = '/w/$1';
$wgUsePathInfo = true;
$wgResourceBasePath = $wgScriptPath;

$wgLogos = [
	'1x' => '/assets/Wiki.png',
	'icon' => '/assets/Wiki.png',
];
$wgFavicon = '/assets/Wiki.png';

$wgEnableEmail = false;
$wgEnableUserEmail = false;

# Database: SQLite, kept in site/data (gitignored).
$wgDBtype = 'sqlite';
$wgDBserver = '';
$wgDBname = 'matchawiki';
$wgDBuser = '';
$wgDBpassword = '';
$wgSQLiteDataDir = '/var/www/data';
$wgObjectCaches[CACHE_DB] = [
	'class' => SqlBagOStuff::class,
	'loggroup' => 'SQLBagOStuff',
	'server' => [
		'type' => 'sqlite',
		'dbname' => 'wikicache',
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0,
	],
];
$wgLocalisationCacheConf['storeServer'] = [
	'type' => 'sqlite',
	'dbname' => "{$wgDBname}_l10n_cache",
	'tablePrefix' => '',
	'variables' => [ 'synchronous' => 'NORMAL' ],
	'dbDirectory' => $wgSQLiteDataDir,
	'trxMode' => 'IMMEDIATE',
	'flags' => 0,
];
$wgJobTypeConf['default'] = [
	'class' => 'JobQueueDB',
	'claimTTL' => 3600,
	'server' => [
		'type' => 'sqlite',
		'dbname' => "{$wgDBname}_jobqueue",
		'tablePrefix' => '',
		'variables' => [ 'synchronous' => 'NORMAL' ],
		'dbDirectory' => $wgSQLiteDataDir,
		'trxMode' => 'IMMEDIATE',
		'flags' => 0,
	],
];
$wgResourceLoaderUseObjectCacheForDeps = true;

$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];
# Build-time renderer: always render fresh so template and data changes show immediately.
$wgParserCacheType = CACHE_NONE;
$wgJobRunRate = 1;

$wgEnableUploads = true;
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp', 'svg' ];
$wgUseImageMagick = false;
$wgUseInstantCommons = false;
$wgPingback = false;

$wgLanguageCode = 'en';
$wgLocaltimezone = 'UTC';
$wgSecretKey = 'b1f6c3d0a7e24c1f9e0d5a8b7c6f4e3d2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d';
$wgAuthenticationTokenVersion = '1';
$wgUpgradeKey = 'matchawikiupgrade';

$wgRightsPage = '';
$wgRightsUrl = 'https://creativecommons.org/licenses/by-nc-sa/4.0/';
$wgRightsText = 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0';
$wgRightsIcon = '';
$wgFooterIcons['copyright'] = [];

$wgDiff3 = '/usr/bin/diff3';

# Read-only renderer. All content lives in git (wiki/pages, generated by tools/) and is
# imported with tools/build.sh — nobody logs in or edits through the web.
foreach ( [ '*', 'user', 'autoconfirmed' ] as $group ) {
	foreach ( [ 'edit', 'createpage', 'createtalk', 'writeapi', 'upload', 'reupload', 'move',
		'createaccount', 'autocreateaccount', 'sendemail', 'editmyoptions' ] as $right ) {
		$wgGroupPermissions[$group][$right] = false;
	}
}
$wgHooks['SkinTemplateNavigation::Universal'][] = static function ( $skin, &$links ) {
	// Hide login/account links and edit tabs: this wiki is edited through git.
	unset( $links['user-menu']['login'], $links['user-menu']['createaccount'],
		$links['user-menu']['anonlogin'], $links['user-menu']['login-private'],
		$links['user-menu']['anoncontribs'], $links['user-menu']['anontalk'] );
	unset( $links['views']['edit'], $links['views']['ve-edit'], $links['views']['viewsource'] );
};

# Skin: Vector (legacy), as on matchaflavoured.wiki.
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MinervaNeue' );
$wgDefaultSkin = 'vector';
$wgVectorResponsive = true;

# Mobile: MobileFrontend with the Minerva skin, as on minecraft.wiki. Phones get the mobile view
# (collapsible sections, the lead paragraph above the infobox, a menu drawer); the static site
# serves it by user agent from src/worker.js. Styled by minecraft.wiki's Minerva CSS
# (Gadget-mcw-minerva.css) and MediaWiki:Minerva.css.
wfLoadExtension( 'MobileFrontend' );
$wgDefaultMobileSkin = 'minerva';
$wgMFAutodetectMobileView = true;
# Same URL for both views: the static export's canonical links and the Worker decide, not MF
$wgMFNoindexPages = false;
# minecraft.wiki keeps navboxes on mobile (restyled by its mobileNavbox CSS)
$wgMFRemovableClasses = [ 'base' => [ '.nomobile' ], 'beta' => [] ];
$wgMFEnableBeta = false;
$wgMFEnableManifest = false;
$wgMFEnableFontChanger = [ 'base' => false, 'beta' => false ];
$wgMFEnableWikidataDescriptions = [ 'base' => false, 'beta' => false ];
$wgMFAdvancedMobileContributions = false;
# Dark mode is minecraft.wiki's wgl-theme-dark toggle (MediaWiki:Gadget-mfwShell.js), which also flips
# Minerva's own night-mode class (skin-theme-clientpref-night) so the skin chrome follows it.
$wgMinervaAlwaysShowLanguageButton = false;
$wgMinervaShowCategories = [ 'base' => true, 'loggedin' => true, 'amc' => true ];

# Extensions — the same parser-side set the reference wiki uses where bundled.
wfLoadExtensions( [
	'CategoryTree',
	'Cite',
	'CodeEditor',
	'Gadgets',
	'ImageMap',
	'InputBox',
	'MultimediaViewer',
	'PageImages',
	'ParserFunctions',
	'Poem',
	'Scribunto',
	'SyntaxHighlight_GeSHi',
	'TemplateData',
	'TemplateStyles',
	'TextExtracts',
	'WikiEditor',
] );
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoEngineConf['luastandalone']['luaPath'] = '/usr/bin/lua5.1';
$wgPFEnableStringFunctions = true;
$wgUseInstantCommons = false;
$wgAllowSiteCSSOnRestrictedPages = true;
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_TEMPLATE] = true;
$wgCapitalLinks = true;
$wgExternalLinkTarget = false;
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgRestrictDisplayTitle = false;
$wgShowExceptionDetails = true;

# Apply the saved light/dark theme before first paint (no flash of the light theme).
$wgHooks['BeforePageDisplay'][] = static function ( $out, $skin ) {
	$out->addHeadItem( 'mfw-theme-boot', '<script>' . trim( file_get_contents( __DIR__ . '/theme-boot.js' ) ) . '</script>' );
};

# Links from every page to its source file on GitHub (see site/GitLinks.php)
require_once __DIR__ . "/GitLinks.php";
